### PR TITLE
Simple settings window

### PR DESCRIPTION
**Pull request by aegroto**
I added a simple settings window to modify hardcoded variables like jmeVersion,review and merge it if it's enough suitable if you want.

### CODE REVIEW

**Comment by aegroto** [comment]
Also,i just saw that jmeVersion was not reported in the readme so i added it in the documentation.

**Comment by Nehon** [comment]
tested it and it works.
But I'm not fond of having it in a separate window.
IMO either you directly add it to the existing dialog either you make some kind of collapsible panel "advanced settings".
The first solution might be very easier though.

**Comment by aegroto** [comment]
As you wish,sir. Check it.

**Comment by Nehon** [comment]
Looking good, thanks for this ;)

**Pull request merged**
